---
apiVersion: v1
kind: Service
metadata:
  name: ms-alertas-headless
  namespace: muni-valle-sol
  labels:
    app: ms-alertas
spec:
  clusterIP: None
  selector:
    app: ms-alertas
  ports:
    - name: http
      port: 8083
      targetPort: http
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Service
metadata:
  name: ms-alertas
  namespace: muni-valle-sol
  labels:
    app: ms-alertas
spec:
  selector:
    app: ms-alertas
  ports:
    - name: http
      port: 8083
      targetPort: http
  type: ClusterIP
